version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  versioning-strategy: lockfile-only
  labels:
  - "gem"
  - "dependencies"
  - "lockfile-only"
  allow:
  - dependency-type: all
  # Create a group of dependencies to be updated together in one pull request
  groups:
    # https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#%E4%BE%8B-2
    # Specify a name for the group, which will be used in pull request titles
    # and branch names
    dev-dependencies:
      # Define patterns to include dependencies in the group (based on
      # dependency name)
      patterns:
      - "rubocop" # A single dependency name
      - "rspec*"  # A wildcard string that matches multiple dependency names
      - "*"       # A wildcard that matches all dependencies in the package
                  # ecosystem. Note: using "*" may open a large pull request
      # Define patterns to exclude dependencies from the group (based on
      # dependency name)
      exclude-patterns:
      - "gc_ruboconfig"
      - "gocardless-*"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  versioning-strategy: lockfile-only
  labels:
  - "gem"
  - "dependencies"
  - "lockfile-only"
  allow:
  - dependency-type: all
  # https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#%E4%BE%8B-3
  groups:
    angular:
      patterns:
      - "@angular*"
      update-types:
      - "minor"
      - "patch"

